/* empty css                      */import{S as m,P as p,A as g}from"./assets/vendor-iT9SqOa9.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function u(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=u(e);fetch(e.href,t)}})();new m(".gallery-swiper",{modules:[p,g],slidesPerView:1,spaceBetween:16,loop:!0,autoplay:{delay:3e3,disableOnInteraction:!1,pauseOnMouseEnter:!0},pagination:{el:".gallery-pagination",clickable:!0}});document.addEventListener("DOMContentLoaded",()=>{const l=document.querySelector(".menu-button"),s=l.querySelector(".icon"),u=document.querySelector(".modal"),a=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const c=`
<svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M5 30V26.6667H35V30H5ZM5 21.6667V18.3333H35V21.6667H5ZM5 13.3333V10H35V13.3333H5Z" fill="white" />
</svg>
    `,o=`
<svg width="40" height="40" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M20 20L4 4M20 4L4 20" stroke="white" stroke-width="2" stroke-linecap="round" />
</svg>
    `;l.addEventListener("click",()=>{t=!t,s.innerHTML=t?o:c,t?n():r()}),a.forEach(d=>d.addEventListener("click",()=>{r(),s.innerHTML=c,t=!1})),window.addEventListener("scroll",i);function n(){u.style.display="block"}function r(){u.style.display="none"}function i(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function l(){const o=document.getElementById("site-header");return o?o.offsetHeight:0}function s(o){const n=document.getElementById(o);if(!n)return;const r=l(),i=n.getBoundingClientRect().top+window.pageYOffset-r;window.scrollTo({top:i,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(o=>{o.addEventListener("click",function(n){const r=this.getAttribute("href");if(!r)return;const[i,d]=r.split("#");if(!d)return;const f=window.location.pathname.split("/").pop();!(i===""||i==="./"||i===f||i==="./"+f)||!document.getElementById(d)||(n.preventDefault(),s(d),t(d))})});const a=document.querySelectorAll("section[id]"),e=document.querySelectorAll(".navigation-item");function t(o){e.forEach(r=>r.classList.remove("active"));const n=document.querySelector(`.navigation-item a[href*="#${o}"]`);n&&n.closest(".navigation-item").classList.add("active")}function c(){const o=window.pageYOffset+l()+100;a.forEach(n=>{const r=n.offsetTop,i=r+n.offsetHeight;o>=r&&o<i&&t(n.id)})}if(window.addEventListener("scroll",c),window.location.hash){const o=window.location.hash.substring(1);setTimeout(()=>{s(o),t(o)},300)}});
//# sourceMappingURL=index.js.map
